// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CustomTextFieldAlertView {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("RootView")]
	public partial class RootView {
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				return ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
			}
			set {
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("button")]
		private MonoTouch.UIKit.UIButton button {
			get {
				return ((MonoTouch.UIKit.UIButton)(this.GetNativeField("button")));
			}
			set {
				this.SetNativeField("button", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("nameLabel")]
		private MonoTouch.UIKit.UILabel nameLabel {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("nameLabel")));
			}
			set {
				this.SetNativeField("nameLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonForClicked")]
		private MonoTouch.UIKit.UIButton buttonForClicked {
			get {
				return ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonForClicked")));
			}
			set {
				this.SetNativeField("buttonForClicked", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("whereLabel")]
		private MonoTouch.UIKit.UILabel whereLabel {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("whereLabel")));
			}
			set {
				this.SetNativeField("whereLabel", value);
			}
		}
	}
}
